Notifying user when there is unmeet dependencies.

diff --git a/grmwl b/grmwl
--- a/grmwl
+++ b/grmwl
@@ -30,49 +30,43 @@ clean_container(){
 	sudo docker ps -a --no-trunc | grep `cat ~/.grmwl/$1/id` | awk '{print $1}' | xargs --no-run-if-empty sudo docker rm -f
 }
 
-
-if ! which collectd 2>&1 >/dev/null; then
-	echo "Installing collectd ..."
-	OS=`lsb-release -si`
-	if [ "$OS" -eq "Ubuntu" ]; then
-		sudo apt-get install collectd -y
-	elif [ "$OS" -eq "Fedora" ]; then
-		sudo yum install collectd -y
+if ! which docker 2>&1 >/dev/null; then
+	echo "Can't run without docker dude."
+elif ! which collectd 2>&1 >/dev/null; then
+	echo "Can't run without collectd either."
+else	
+	if [ "$1" = "create" ]; then
+		if [ -x ~/.grmwl/$2/id ]; then
+			echo "Project already created."
+		else
+			echo "Creating project $2..."
+			pull
+			build $2
+		fi
+	
+	elif [ "$1" = "run" ]; then
+		if [ -x ~/.grmwl/$2/id ]; then
+			echo "Project does not exist, you need to create it first ($0 create $2)"
+		else
+			echo "Running project $2..."
+			run $2
+		fi
+	elif [ "$1" = "stop" ]; then
+		if [ -x ~/.grmwl/$2/id ]; then
+			echo "Project does not exist, you need to create it first ($0 create $2)"
+		else
+			echo "Stopping project $2..."
+			stop $2
+		fi
+	elif [ "$1" = "delete" ]; then
+		if [ -x ~/.grmwl/$2/id ]; then
+			echo "Project $2 does not exist."
+		else
+			echo "Deleting project $2..."
+			clean_container $2
+			sudo rm ~/.grmwl/$2 -R
+		fi
 	else
-		echo "Unknown OS, please install collectd manually."
-	fi 
-fi	
-if [ "$1" = "create" ]; then
-	if [ -x ~/.grmwl/$2/id ]; then
-		echo "Project already created."
-	else
-		echo "Creating project $2..."
-		pull
-		build $2
+		echo "Usage : (create,run,delete) project"
 	fi
-
-elif [ "$1" = "run" ]; then
-	if [ -x ~/.grmwl/$2/id ]; then
-		echo "Project does not exist, you need to create it first ($0 create $2)"
-	else
-		echo "Running project $2..."
-		run $2
-	fi
-elif [ "$1" = "stop" ]; then
-	if [ -x ~/.grmwl/$2/id ]; then
-		echo "Project does not exist, you need to create it first ($0 create $2)"
-	else
-		echo "Stopping project $2..."
-		stop $2
-	fi
-elif [ "$1" = "delete" ]; then
-	if [ -x ~/.grmwl/$2/id ]; then
-		echo "Project $2 does not exist."
-	else
-		echo "Deleting project $2..."
-		clean_container $2
-		sudo rm ~/.grmwl/$2 -R
-	fi
-else
-	echo "Usage : (create,run,delete) project"
 fi
